// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jurllurbxgwptihrtjmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1cmxsdXJieGd3cHRpaHJ0am1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTY4MDYsImV4cCI6MjA1OTM3MjgwNn0.60W7G04DlbPijvhUiTaNUPM893M4UUj5WK3AYKZc-Vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);